# numerical python

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.zeros((3,4))

In [3]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
a = np.array([1,2,3,7])

In [7]:
arr+a

array([[1., 2., 3., 7.],
       [1., 2., 3., 7.],
       [1., 2., 3., 7.]])

In [20]:
b = np.array([[1,2,5]])

In [21]:
b.shape

(1, 3)

In [25]:
b.reshape(3,1)

array([[1],
       [2],
       [5]])

In [26]:
p = b.T

In [27]:
p.shape

(3, 1)

In [24]:
p+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [30]:
#exploring random module
np.random.seed(90)
np.random.randint(4,6,(4,5,9))

array([[[5, 5, 4, 5, 5, 5, 4, 4, 5],
        [4, 4, 4, 5, 5, 4, 4, 4, 5],
        [4, 5, 4, 4, 4, 5, 4, 4, 5],
        [4, 4, 4, 5, 4, 4, 5, 4, 5],
        [4, 5, 4, 5, 4, 4, 5, 4, 5]],

       [[5, 4, 4, 4, 4, 4, 4, 5, 5],
        [4, 4, 5, 4, 4, 4, 5, 4, 5],
        [5, 4, 5, 5, 5, 4, 5, 5, 4],
        [5, 5, 4, 5, 5, 4, 4, 5, 5],
        [4, 4, 4, 4, 5, 4, 5, 5, 5]],

       [[4, 5, 4, 4, 5, 4, 4, 5, 5],
        [4, 5, 5, 5, 4, 5, 4, 5, 4],
        [5, 5, 4, 4, 5, 4, 4, 5, 5],
        [5, 5, 5, 5, 4, 4, 5, 4, 4],
        [5, 5, 4, 4, 4, 5, 4, 5, 5]],

       [[5, 4, 5, 4, 4, 4, 5, 5, 5],
        [4, 4, 5, 5, 4, 5, 5, 4, 4],
        [4, 4, 5, 4, 4, 4, 4, 4, 4],
        [5, 4, 5, 4, 5, 4, 5, 4, 5],
        [4, 5, 4, 5, 5, 5, 5, 4, 4]]])

In [32]:
np.random.rand(4,5)

array([[0.89856542, 0.29158325, 0.09232334, 0.85285344, 0.24930173],
       [0.84562832, 0.03655504, 0.97849449, 0.51743013, 0.98264974],
       [0.90746414, 0.61165095, 0.70724051, 0.28385982, 0.40861216],
       [0.38379601, 0.52713777, 0.72033661, 0.5349447 , 0.94907888]])

In [51]:
blur = np.random.randn(2,4,8) #three dimension array

In [52]:
blur

array([[[ 0.63589108,  1.74011731,  0.29668222,  0.70750366,
          1.82281576,  0.43076903,  1.54272963, -0.90072117],
        [-0.13712501,  1.29757901,  0.67527117,  0.03195812,
          0.9181459 ,  0.38050947,  0.51636749, -0.35523946],
        [ 0.208777  ,  0.32841108, -0.49822477, -2.09177677,
         -0.08258774,  2.45518265, -2.67211   , -0.91327928],
        [-0.22731436,  0.26931538,  1.13046126,  1.04239745,
          1.30381044,  1.38940073, -0.65645258, -0.0562573 ]],

       [[-0.49990262,  0.43641938, -0.37581305, -0.92306158,
          1.91725024, -0.15030284, -0.63872976,  0.82477033],
        [-1.21083874, -0.50340538, -0.70191569, -1.97427103,
         -2.65573217, -0.05768225, -0.65618659, -0.66170671],
        [ 0.76934844, -0.89900489,  1.69363792, -1.69733524,
         -2.79337021, -0.22615065,  0.39742884,  1.65970362],
        [-0.49374681, -0.37609768, -0.16973977,  2.41710632,
         -1.80884049,  0.33975115, -0.02272976, -0.95999708]]])

In [54]:
blur.max()

2.4551826523000084

In [55]:
blur.min()

-2.7933702050352007

In [44]:
np.random.seed(9)
nino = np.random.random(10)

In [45]:
np.sqrt(nino)

array([0.10185359, 0.70843108, 0.70411171, 0.36582718, 0.37697624,
       0.46750259, 0.64692208, 0.49809755, 0.28993042, 0.58779132])

In [47]:
cito = np.exp(nino)

In [48]:
cito

array([1.01042815, 1.65181485, 1.64176732, 1.14319792, 1.15270469,
       1.24428202, 1.51969276, 1.28158958, 1.08769377, 1.41269417])

In [49]:
cito.max()

1.651814849342831

In [50]:
cito.min()

1.010428151986785

In [56]:
np.array([[[1,3],[5,6]],[[2,7],[9,3]]])

array([[[1, 3],
        [5, 6]],

       [[2, 7],
        [9, 3]]])

In [58]:
np.array([1,5,9],ndmin = 3)

array([[[1, 5, 9]]])

In [59]:
np.array([1,5,9],ndmin = 3,dtype ='complex' )

array([[[1.+0.j, 5.+0.j, 9.+0.j]]])

In [61]:
np.array([[(1,2),(7,9)]])

array([[[1, 2],
        [7, 9]]])

In [62]:
np.array([(5,7,8),(4,6,9)])

array([[5, 7, 8],
       [4, 6, 9]])

In [66]:
arey =np.mat([(4,7,9),(1,5,4)])

In [67]:
arey

matrix([[4, 7, 9],
        [1, 5, 4]])

In [68]:
np.asarray(arey)

array([[4, 7, 9],
       [1, 5, 4]])

In [69]:
np.asanyarray(arey)

matrix([[4, 7, 9],
        [1, 5, 4]])

In [70]:
zinda = np.array([(1,5,4),(8,6,3)],dtype = [('a','<i2'),('b','<i4'),('c','<i8')])

In [71]:
zinda

array([(1, 5, 4), (8, 6, 3)],
      dtype=[('a', '<i2'), ('b', '<i4'), ('c', '<i8')])

In [74]:
zinda[1][0].dtype

dtype('int16')

In [75]:
c = zinda

In [78]:
c

array([(1, 5, 4), (8, 6, 3)],
      dtype=[('a', '<i2'), ('b', '<i4'), ('c', '<i8')])

In [76]:
v = np.copy(zinda)

In [77]:
v

array([(1, 5, 4), (8, 6, 3)],
      dtype=[('a', '<i2'), ('b', '<i4'), ('c', '<i8')])

In [79]:
zinda[1][1] = 5

In [80]:
c

array([(1, 5, 4), (8, 5, 3)],
      dtype=[('a', '<i2'), ('b', '<i4'), ('c', '<i8')])

In [81]:
v

array([(1, 5, 4), (8, 6, 3)],
      dtype=[('a', '<i2'), ('b', '<i4'), ('c', '<i8')])

In [86]:
issubclass(np.matrix,np.ndarray)

True

In [87]:
np.fromfunction(lambda i ,j : i == j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [89]:
np.fromfunction(lambda i,j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [90]:
np.fromiter(range(5),dtype = int)

array([0, 1, 2, 3, 4])

In [92]:
gen = (i*i for i in range(6))
np.fromiter(gen,dtype = int)

array([ 0,  1,  4,  9, 16, 25])

In [97]:
np.fromstring('1,8,6,7,2,44,34',sep = ',',dtype = int)

array([ 1,  8,  6,  7,  2, 44, 34])

In [98]:
np.fromstring('487 258 987 347 456',sep = ' ', dtype = complex)

array([487.+0.j, 258.+0.j, 987.+0.j, 347.+0.j, 456.+0.j])

In [99]:
aur = np.array([[1,8,9,6],[2,6,7,1],[4,3,7,8],[8,5,2,4]])

In [100]:
aur

array([[1, 8, 9, 6],
       [2, 6, 7, 1],
       [4, 3, 7, 8],
       [8, 5, 2, 4]])

In [101]:
aur.ndim

2

In [102]:
aur.size

16

In [103]:
aur.shape

(4, 4)

In [104]:
type(arr)

numpy.ndarray

In [105]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
np.linspace(1,8,12)

array([1.        , 1.63636364, 2.27272727, 2.90909091, 3.54545455,
       4.18181818, 4.81818182, 5.45454545, 6.09090909, 6.72727273,
       7.36363636, 8.        ])

In [109]:
np.empty((2,2))

array([[1. , 0.5],
       [2. , 1. ]])

In [110]:
np.empty([4,5])

array([[0.89856542, 0.29158325, 0.09232334, 0.85285344, 0.24930173],
       [0.84562832, 0.03655504, 0.97849449, 0.51743013, 0.98264974],
       [0.90746414, 0.61165095, 0.70724051, 0.28385982, 0.40861216],
       [0.38379601, 0.52713777, 0.72033661, 0.5349447 , 0.94907888]])

In [113]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [114]:
np.zeros([4,5,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [117]:
np.linspace(4,6,num=8,endpoint=True)

array([4.        , 4.28571429, 4.57142857, 4.85714286, 5.14285714,
       5.42857143, 5.71428571, 6.        ])

In [120]:
np.logspace(2,5,10000)

array([   100.        ,    100.06910833,    100.13826442, ...,
        99861.92648684,  99930.93939658, 100000.        ])

#                                         PANDAS

In [2]:
jam = pd.read_excel('D:\my sample dataset file\\sampledatasafety.xlsx',sheet_name = 'SafetyData')

In [3]:
jam

,Date,Injury Location,Gender,Age Group,Incident_Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,2020-01-01,Multiple,Male,25-34,Burn,0.0,Iowa,Near Miss,Afternoon,Painting,0,Wed,1,2020
1,2020-01-03,NaN,Male,35-49,Vehicle,0.5,Alabama,Lost Time,Day,Fabrication,3367,Fri,1,2020
2,2020-01-03,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,0,Fri,1,2020
3,2020-01-04,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,0,Sat,1,2020
4,2020-01-07,Legs,Male,25-34,Lifting,0.0,Ohio,Near Miss,Day,Painting,0,Tue,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,2022-06-26,Head,Female,25-34,Crush & Pinch,0.0,California,First Aid,Night,Administration,77,Sun,6,2022
510,2022-06-27,Hands,Male,25-34,Lifting,0.0,Florida,Near Miss,Afternoon,Melting,0,Mon,6,2022
511,2022-06-28,Hands,Male,25-34,Cut,0.0,Florida,Near Miss,Afternoon,Purchasing,0,Tue,6,2022
512,2022-06-28,Trunk,Male,50+,Falling object,0.0,Florida,Medical Claim,Night,Administration,804,Tue,6,2022
513,2022-06-28,Hands,Male,18-24,Vehicle,0.0,Texas,Medical Claim,Afternoon,Melting,706,Tue,6,2022

In [4]:
jam.drop('Date',axis = 1,inplace = True)

In [5]:
jam

,Injury Location,Gender,Age Group,Incident_Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,Multiple,Male,25-34,Burn,0.0,Iowa,Near Miss,Afternoon,Painting,0,Wed,1,2020
1,NaN,Male,35-49,Vehicle,0.5,Alabama,Lost Time,Day,Fabrication,3367,Fri,1,2020
2,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,0,Fri,1,2020
3,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,0,Sat,1,2020
4,Legs,Male,25-34,Lifting,0.0,Ohio,Near Miss,Day,Painting,0,Tue,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,Head,Female,25-34,Crush & Pinch,0.0,California,First Aid,Night,Administration,77,Sun,6,2022
510,Hands,Male,25-34,Lifting,0.0,Florida,Near Miss,Afternoon,Melting,0,Mon,6,2022
511,Hands,Male,25-34,Cut,0.0,Florida,Near Miss,Afternoon,Purchasing,0,Tue,6,2022
512,Trunk,Male,50+,Falling object,0.0,Florida,Medical Claim,Night,Administration,804,Tue,6,2022
513,Hands,Male,18-24,Vehicle,0.0,Texas,Medical Claim,Afternoon,Melting,706,Tue,6,2022

In [6]:
jam.describe()

        Days Lost  Incident Cost       Month         Year
count  514.000000     514.000000  514.000000   514.000000
mean     0.736381    1396.488327    5.867704  2020.749027
std      1.443565    1604.765105    3.386421     0.739612
min      0.000000       0.000000    1.000000  2020.000000
25%      0.000000       0.000000    3.000000  2020.000000
50%      0.000000     512.500000    5.000000  2021.000000
75%      0.500000    2519.250000    8.000000  2021.000000
max      5.000000    5000.000000   12.000000  2022.000000

In [7]:
m = jam[jam['Gender'] == 'Male']

In [8]:
f = jam[jam['Gender'] == 'Female']

In [9]:
f

,Injury Location,Gender,Age Group,Incident_Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
3,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,0,Sat,1,2020
5,NaN,Female,50+,Crush & Pinch,0.0,Georgia,First Aid,Afternoon,Security,132,Sat,1,2020
10,NaN,Female,35-49,Falling object,0.0,Iowa,First Aid,Night,Shipping,59,Sat,1,2020
31,Multiple,Female,35-49,Fall,2.0,Ohio,Lost Time,Night,Maintenance,2544,Mon,2,2020
32,Multiple,Female,35-49,Equipment,0.0,Montana,Medical Claim,Day,Administration,3411,Wed,2,2020
44,Neck,Female,18-24,Fall,0.0,Florida,Medical Claim,Day,Administration,4933,Thu,3,2020
56,Eye,Female,50+,Vehicle,4.5,Alabama,Lost Time,Night,Fabrication,1152,Mon,4,2020
65,Head,Female,18-24,Vehicle,4.0,Texas,Lost Time,Afternoon,Shipping,3680,Tue,4,2020
69,Eye,Female,50+,Equipment,0.0,Montana,Near Miss,Day,Purchasing,0,Sat,4,2020
70,Trunk,Female,18-24,Slip/trip,0.0,California,Near Miss,Day,Purchasing,0,Mon,4,2020
103,Head,Female,25-34,Falling object,0.0,California,Medical Claim,Day,Fabrication,4016,Fri,6,2020
107,Feet,Female,25-34,Equipment,2.0,Alabama,Lost Time,Day,Melting,1635,Sun,6,2020
111,NaN,Female,50+,Equipment,0.0,Ohio,First Aid,Day,Melting,250,Mon,7,2020
129,NaN,Female,35-49,Falling object,0.0,Ohio,Near Miss,Night,Shipping,0,Thu,7,2020
136,Trunk,Female,25-34,Slip/trip,0.0,Texas,Near Miss,Day,Melting,0,Mon,8,2020
140,Trunk,Female,35-49,Cut,0.0,Montana,Near Miss,Afternoon,Maintenance,0,Thu,8,2020
145,Hands,Female,35-49,Cut,0.0,Illinois,Near Miss,Night,Painting,0,Sun,8,2020
149,Hands,Female,35-49,Lifting,0.0,California,First Aid,Afternoon,Maintenance,88,Thu,8,2020
151,Hands,Female,18-24,Slip/trip,2.5,Ohio,Lost Time,Night,Finishing,3488,Mon,8,2020
152,NaN,Female,25-34,Cut,0.0,Texas,First Aid,Day,Administration,351,Sat,9,2020
158,Feet,Female,35-49,Lifting,0.0,Texas,Medical Claim,Day,Fabrication,1819,Wed,9,2020
189,Back,Female,35-49,Burn,0.0,California,First Aid,Night,Finishing,244,Fri,11,2020
191,Abdomen,Female,25-34,Falling object,5.0,California,Lost Time,Day,Fabrication,4879,Sun,11,2020
192,Back,Female,18-24,Lifting,0.0,Illinois,First Aid,Night,Maintenance,414,Tue,11,2020
193,Abdomen,Female,25-34,Burn,5.0,Montana,Lost Time,Day,Shipping,2569,Wed,11,2020
199,Arms,Female,25-34,Burn,1.0,Georgia,Lost Time,Afternoon,Maintenance,2877,Fri,12,2020
221,Arms,Female,50+,Crush & Pinch,0.0,Alabama,Medical Claim,Afternoon,Finishing,503,Sun,1,2021
222,Abdomen,Female,25-34,Crush & Pinch,0.0,Georgia,Medical Claim,Afternoon,Painting,3846,Sun,1,2021
237,Back,Female,50+,Vehicle,0.0,Alabama,Near Miss,Day,Painting,0,Tue,2,2021
246,Neck,Female,25-34,Slip/trip,0.0,Florida,Near Miss,Night,Shipping,0,Thu,2,2021
257,Legs,Female,35-49,Equipment,0.0,California,First Aid,Night,Painting,84,Thu,3,2021
263,Feet,Female,25-34,Burn,5.0,Iowa,Lost Time,Day,Maintenance,4373,Wed,3,2021
265,Feet,Female,25-34,Equipment,0.0,Alabama,First Aid,Afternoon,Melting,217,Fri,3,2021
269,Eye,Female,18-24,Vehicle,5.0,Ohio,Lost Time,Night,Melting,1993,Wed,3,2021
272,Back,Female,25-34,Slip/trip,0.0,Ohio,First Aid,Night,Administration,342,Fri,4,2021
279,Eye,Female,25-34,Burn,0.0,Illinois,Near Miss,Night,Administration,0,Thu,4,2021
295,Feet,Female,18-24,Equipment,0.0,Montana,Medical Claim,Afternoon,Shipping,3286,Wed,5,2021
299,Head,Female,50+,Burn,0.0,Montana,Near Miss,Afternoon,Administration,0,Mon,5,2021
308,Abdomen,Female,18-24,Vehicle,3.0,California,Lost Time,Afternoon,Security,498,Thu,6,2021
354,Head,Female,18-24,Slip/trip,0.0,Texas,Near Miss,Day,Painting,0,Thu,8,2021
360,Head,Female,35-49,Burn,0.0,Texas,Near Miss,Afternoon,Maintenance,0,Tue,8,2021
366,Legs,Female,50+,Falling object,0.0,Texas,Medical Claim,Day,Finishing,1433,Mon,9,2021
375,Hands,Female,50+,Cut,0.0,California,First Aid,Night,Purchasing,238,Tue,9,2021
378,Multiple,Female,25-34,Vehicle,0.0,Montana,Near Miss,Afternoon,Painting,0,Fri,10,2021
384,NaN,Female,50+,Equipment,4.0,Texas,Lost Time,Afternoon,Painting,2622,Fri,10,2021
399,Hands,Female,35-49,Cut,0.5,California,Lost Time,Afternoon,Painting,920,Sun,11,2021
403,Back,Female,35-49,Fall,0.0,Ohio,Near Miss,Afternoon,Purchasing,0,Wed,11,2021
409,Eye,Female,50+,Fall,0.0,Alabama,First Aid,Day,Administration,449,Sun,11,2021
411,Feet,Female,25-34,Lifting,0.0,Florida,Near Miss,Day,Purchasing,0,Fri,12,2021
427,Back,Female,35-49,Lifting,4.0,Alabama,Lost Time,Night,Security,736,Sun,1,2022
441,Eye,Female,35-49,Equipment,5.0,Ohio,Lost Time,Day,Shipping,1919,Sun,1,2022
456,Eye,Female,50+,Crush & Pinch,4.0,Iowa,Lost Time,Afternoon,Purchasing,1594,Wed,2,2022
459,Multiple,Female,25-34,Cut,0.0,Ohio,Medical Claim,Night,Purchasing,2793,Sat,2,2022
489,Back,Female,35-49,Vehicle,0.0,Illinois,Medical Claim,Afternoon,Administration,2795,Tue,5,2022
507,Multiple,Female,50+,Slip/trip,0.0,Florida,Medical Claim,Day,Administration,2356,Fri,6,2022
509,Head,Female,25-34,Crush & Pinch,0.0,California,First Aid,Night,Administration,77,Sun,6,2022

In [10]:
f.groupby(['Plant','Injury Location','Department','Incident_Type']).count()

                                                          Gender  Age Group  \
Plant      Injury Location Department     Incident_Type
Alabama    Arms            Finishing      Crush & Pinch        1          1
           Back            Painting       Vehicle              1          1
                           Security       Lifting              1          1
           Eye             Administration Fall                 1          1
                           Fabrication    Vehicle              1          1
           Feet            Melting        Equipment            2          2
California Abdomen         Fabrication    Falling object       1          1
                           Security       Vehicle              1          1
           Back            Finishing      Burn                 1          1
           Hands           Maintenance    Lifting              1          1
                           Painting       Cut                  1          1
                           Purchasing     Cut                  1          1
           Head            Administration Crush & Pinch        1          1
                           Fabrication    Falling object       1          1
           Legs            Painting       Equipment            1          1
           Trunk           Purchasing     Slip/trip            1          1
Florida    Feet            Purchasing     Lifting              1          1
           Multiple        Administration Slip/trip            1          1
           Neck            Administration Fall                 1          1
                           Shipping       Slip/trip            1          1
Georgia    Abdomen         Painting       Crush & Pinch        1          1
           Arms            Maintenance    Burn                 1          1
Illinois   Back            Administration Vehicle              1          1
                           Maintenance    Lifting              1          1
           Eye             Administration Burn                 1          1
           Hands           Painting       Cut                  1          1
Iowa       Eye             Purchasing     Crush & Pinch        1          1
           Feet            Maintenance    Burn                 1          1
           Legs            Painting       Falling object       1          1
Montana    Abdomen         Shipping       Burn                 1          1
           Eye             Purchasing     Equipment            1          1
           Feet            Shipping       Equipment            1          1
           Head            Administration Burn                 1          1
           Multiple        Administration Equipment            1          1
                           Painting       Vehicle              1          1
           Trunk           Maintenance    Cut                  1          1
Ohio       Back            Administration Slip/trip            1          1
                           Purchasing     Fall                 1          1
           Eye             Melting        Vehicle              1          1
                           Shipping       Equipment            1          1
           Hands           Finishing      Slip/trip            1          1
           Multiple        Maintenance    Fall                 1          1
                           Purchasing     Cut                  1          1
Texas      Feet            Fabrication    Lifting              1          1
           Head            Maintenance    Burn                 1          1
                           Painting       Slip/trip            1          1
                           Shipping       Vehicle              1          1
           Legs            Finishing      Falling object       1          1
           Trunk           Melting        Slip/trip            1          1

                                                          Days Lost  \
Plant      Injury Location Department     Incident_Type
Alabama    Arms            Finishing      Crush & Pinch           1
           Back            Painting       Vehicle                 1
                           Security       Lifting                 1
           Eye             Administration Fall                    1
                           Fabrication    Vehicle                 1
           Feet            Melting        Equipment               2
California Abdomen         Fabrication    Falling object          1
                           Security       Vehicle                 1
           Back            Finishing      Burn                    1
           Hands           Maintenance    Lifting                 1
                           Painting       Cut                     1
                           Purchasing     Cut                     1
           Head            Administration Crush & Pinch           1
                           Fabrication    Falling object          1
           Legs            Painting       Equipment               1
           Trunk           Purchasing     Slip/trip               1
Florida    Feet            Purchasing     Lifting                 1
           Multiple        Administration Slip/trip               1
           Neck            Administration Fall                    1
                           Shipping       Slip/trip               1
Georgia    Abdomen         Painting       Crush & Pinch           1
           Arms            Maintenance    Burn                    1
Illinois   Back            Administration Vehicle                 1
                           Maintenance    Lifting                 1
           Eye             Administration Burn                    1
           Hands           Painting       Cut                     1
Iowa       Eye             Purchasing     Crush & Pinch           1
           Feet            Maintenance    Burn                    1
           Legs            Painting       Falling object          1
Montana    Abdomen         Shipping       Burn                    1
           Eye             Purchasing     Equipment               1
           Feet            Shipping       Equipment               1
           Head            Administration Burn                    1
           Multiple        Administration Equipment               1
                           Painting       Vehicle                 1
           Trunk           Maintenance    Cut                     1
Ohio       Back            Administration Slip/trip               1
                           Purchasing     Fall                    1
           Eye             Melting        Vehicle                 1
                           Shipping       Equipment               1
           Hands           Finishing      Slip/trip               1
           Multiple        Maintenance    Fall                    1
                           Purchasing     Cut                     1
Texas      Feet            Fabrication    Lifting                 1
           Head            Maintenance    Burn                    1
                           Painting       Slip/trip               1
                           Shipping       Vehicle                 1
           Legs            Finishing      Falling object          1
           Trunk           Melting        Slip/trip               1

                                                          Report Type  Shift  \
Plant      Injury Location Department     Incident_Type
Alabama    Arms            Finishing      Crush & Pinch             1      1
           Back            Painting       Vehicle                   1      1
                           Security       Lifting                   1      1
           Eye             Administration Fall                      1      1
                           Fabrication    Vehicle                   1      1
           Feet            Melting        Equipment                 2      2
California Abdomen         Fabrication    Falling object            1      1
                           Security       Vehicle                   1      1
           Back            Finishing      Burn                      1      1
           Hands           Maintenance    Lifting                   1      1
                           Painting       Cut                       1      1
                           Purchasing     Cut                       1      1
           Head            Administration Crush & Pinch             1      1
                           Fabrication    Falling object            1      1
           Legs            Painting       Equipment                 1      1
           Trunk           Purchasing     Slip/trip                 1      1
Florida    Feet            Purchasing     Lifting                   1      1
           Multiple        Administration Slip/trip                 1      1
           Neck            Administration Fall                      1      1
                           Shipping       Slip/trip                 1      1
Georgia    Abdomen         Painting       Crush & Pinch             1      1
           Arms            Maintenance    Burn                      1      1
Illinois   Back            Administration Vehicle                   1      1
                           Maintenance    Lifting                   1      1
           Eye             Administration Burn                      1      1
           Hands           Painting       Cut                       1      1
Iowa       Eye             Purchasing     Crush & Pinch             1      1
           Feet            Maintenance    Burn                      1      1
           Legs            Painting       Falling object            1      1
Montana    Abdomen         Shipping       Burn                      1      1
           Eye             Purchasing     Equipment                 1      1
           Feet            Shipping       Equipment                 1      1
           Head            Administration Burn                      1      1
           Multiple        Administration Equipment                 1      1
                           Painting       Vehicle                   1      1
           Trunk           Maintenance    Cut                       1      1
Ohio       Back            Administration Slip/trip                 1      1
                           Purchasing     Fall                      1      1
           Eye             Melting        Vehicle                   1      1
                           Shipping       Equipment                 1      1
           Hands           Finishing      Slip/trip                 1      1
           Multiple        Maintenance    Fall                      1      1
                           Purchasing     Cut                       1      1
Texas      Feet            Fabrication    Lifting                   1      1
           Head            Maintenance    Burn                      1      1
                           Painting       Slip/trip                 1      1
                           Shipping       Vehicle                   1      1
           Legs            Finishing      Falling object            1      1
           Trunk           Melting        Slip/trip                 1      1

                                                          Incident Cost  \
Plant      Injury Location Department     Incident_Type
Alabama    Arms            Finishing      Crush & Pinch               1
           Back            Painting       Vehicle                     1
                           Security       Lifting                     1
           Eye             Administration Fall                        1
                           Fabrication    Vehicle                     1
           Feet            Melting        Equipment                   2
California Abdomen         Fabrication    Falling object              1
                           Security       Vehicle                     1
           Back            Finishing      Burn                        1
           Hands           Maintenance    Lifting                     1
                           Painting       Cut                         1
                           Purchasing     Cut                         1
           Head            Administration Crush & Pinch               1
                           Fabrication    Falling object              1
           Legs            Painting       Equipment                   1
           Trunk           Purchasing     Slip/trip                   1
Florida    Feet            Purchasing     Lifting                     1
           Multiple        Administration Slip/trip                   1
           Neck            Administration Fall                        1
                           Shipping       Slip/trip                   1
Georgia    Abdomen         Painting       Crush & Pinch               1
           Arms            Maintenance    Burn                        1
Illinois   Back            Administration Vehicle                     1
                           Maintenance    Lifting                     1
           Eye             Administration Burn                        1
           Hands           Painting       Cut                         1
Iowa       Eye             Purchasing     Crush & Pinch               1
           Feet            Maintenance    Burn                        1
           Legs            Painting       Falling object              1
Montana    Abdomen         Shipping       Burn                        1
           Eye             Purchasing     Equipment                   1
           Feet            Shipping       Equipment                   1
           Head            Administration Burn                        1
           Multiple        Administration Equipment                   1
                           Painting       Vehicle                     1
           Trunk           Maintenance    Cut                         1
Ohio       Back            Administration Slip/trip                   1
                           Purchasing     Fall                        1
           Eye             Melting        Vehicle                     1
                           Shipping       Equipment                   1
           Hands           Finishing      Slip/trip                   1
           Multiple        Maintenance    Fall                        1
                           Purchasing     Cut                         1
Texas      Feet            Fabrication    Lifting                     1
           Head            Maintenance    Burn                        1
                           Painting       Slip/trip                   1
                           Shipping       Vehicle                     1
           Legs            Finishing      Falling object              1
           Trunk           Melting        Slip/trip                   1

                                                          WkDay  Month  Year
Plant      Injury Location Department     Incident_Type
Alabama    Arms            Finishing      Crush & Pinch       1      1     1
           Back            Painting       Vehicle             1      1     1
                           Security       Lifting             1      1     1
           Eye             Administration Fall                1      1     1
                           Fabrication    Vehicle             1      1     1
           Feet            Melting        Equipment           2      2     2
California Abdomen         Fabrication    Falling object      1      1     1
                           Security       Vehicle             1      1     1
           Back            Finishing      Burn                1      1     1
           Hands           Maintenance    Lifting             1      1     1
                           Painting       Cut                 1      1     1
                           Purchasing     Cut                 1      1     1
           Head            Administration Crush & Pinch       1      1     1
                           Fabrication    Falling object      1      1     1
           Legs            Painting       Equipment           1      1     1
           Trunk           Purchasing     Slip/trip           1      1     1
Florida    Feet            Purchasing     Lifting             1      1     1
           Multiple        Administration Slip/trip           1      1     1
           Neck            Administration Fall                1      1     1
                           Shipping       Slip/trip           1      1     1
Georgia    Abdomen         Painting       Crush & Pinch       1      1     1
           Arms            Maintenance    Burn                1      1     1
Illinois   Back            Administration Vehicle             1      1     1
                           Maintenance    Lifting             1      1     1
           Eye             Administration Burn                1      1     1
           Hands           Painting       Cut                 1      1     1
Iowa       Eye             Purchasing     Crush & Pinch       1      1     1
           Feet            Maintenance    Burn                1      1     1
           Legs            Painting       Falling object      1      1     1
Montana    Abdomen         Shipping       Burn                1      1     1
           Eye             Purchasing     Equipment           1      1     1
           Feet            Shipping       Equipment           1      1     1
           Head            Administration Burn                1      1     1
           Multiple        Administration Equipment           1      1     1
                           Painting       Vehicle             1      1     1
           Trunk           Maintenance    Cut                 1      1     1
Ohio       Back            Administration Slip/trip           1      1     1
                           Purchasing     Fall                1      1     1
           Eye             Melting        Vehicle             1      1     1
                           Shipping       Equipment           1      1     1
           Hands           Finishing      Slip/trip           1      1     1
           Multiple        Maintenance    Fall                1      1     1
                           Purchasing     Cut                 1      1     1
Texas      Feet            Fabrication    Lifting             1      1     1
           Head            Maintenance    Burn                1      1     1
                           Painting       Slip/trip           1      1     1
                           Shipping       Vehicle             1      1     1
           Legs            Finishing      Falling object      1      1     1
           Trunk           Melting        Slip/trip           1      1     1

In [11]:
f.groupby(['Plant','WkDay','Injury Location','Age Group']).count()

                                            Gender  Incident_Type  Days Lost  \
Plant      WkDay Injury Location Age Group
Alabama    Fri   Feet            25-34           1              1          1
           Mon   Eye             50+             1              1          1
           Sun   Arms            50+             1              1          1
                 Back            35-49           1              1          1
                 Eye             50+             1              1          1
                 Feet            25-34           1              1          1
           Tue   Back            50+             1              1          1
California Fri   Back            35-49           1              1          1
                 Head            25-34           1              1          1
           Mon   Trunk           18-24           1              1          1
           Sun   Abdomen         25-34           1              1          1
                 Hands           35-49           1              1          1
                 Head            25-34           1              1          1
           Thu   Abdomen         18-24           1              1          1
                 Hands           35-49           1              1          1
                 Legs            35-49           1              1          1
           Tue   Hands           50+             1              1          1
Florida    Fri   Feet            25-34           1              1          1
                 Multiple        50+             1              1          1
           Thu   Neck            18-24           1              1          1
                                 25-34           1              1          1
Georgia    Fri   Arms            25-34           1              1          1
           Sun   Abdomen         25-34           1              1          1
Illinois   Sun   Hands           35-49           1              1          1
           Thu   Eye             25-34           1              1          1
           Tue   Back            18-24           1              1          1
                                 35-49           1              1          1
Iowa       Sat   Legs            50+             1              1          1
           Wed   Eye             50+             1              1          1
                 Feet            25-34           1              1          1
Montana    Fri   Multiple        25-34           1              1          1
           Mon   Head            50+             1              1          1
           Sat   Eye             50+             1              1          1
           Thu   Trunk           35-49           1              1          1
           Wed   Abdomen         25-34           1              1          1
                 Feet            18-24           1              1          1
                 Multiple        35-49           1              1          1
Ohio       Fri   Back            25-34           1              1          1
           Mon   Hands           18-24           1              1          1
                 Multiple        35-49           1              1          1
           Sat   Multiple        25-34           1              1          1
           Sun   Eye             35-49           1              1          1
           Wed   Back            35-49           1              1          1
                 Eye             18-24           1              1          1
Texas      Mon   Legs            50+             1              1          1
                 Trunk           25-34           1              1          1
           Thu   Head            18-24           1              1          1
           Tue   Head            18-24           1              1          1
                                 35-49           1              1          1
           Wed   Feet            35-49           1              1          1

                                            Report Type  Shift  Department  \
Plant      WkDay Injury Location Age Group
Alabama    Fri   Feet            25-34                1      1           1
           Mon   Eye             50+                  1      1           1
           Sun   Arms            50+                  1      1           1
                 Back            35-49                1      1           1
                 Eye             50+                  1      1           1
                 Feet            25-34                1      1           1
           Tue   Back            50+                  1      1           1
California Fri   Back            35-49                1      1           1
                 Head            25-34                1      1           1
           Mon   Trunk           18-24                1      1           1
           Sun   Abdomen         25-34                1      1           1
                 Hands           35-49                1      1           1
                 Head            25-34                1      1           1
           Thu   Abdomen         18-24                1      1           1
                 Hands           35-49                1      1           1
                 Legs            35-49                1      1           1
           Tue   Hands           50+                  1      1           1
Florida    Fri   Feet            25-34                1      1           1
                 Multiple        50+                  1      1           1
           Thu   Neck            18-24                1      1           1
                                 25-34                1      1           1
Georgia    Fri   Arms            25-34                1      1           1
           Sun   Abdomen         25-34                1      1           1
Illinois   Sun   Hands           35-49                1      1           1
           Thu   Eye             25-34                1      1           1
           Tue   Back            18-24                1      1           1
                                 35-49                1      1           1
Iowa       Sat   Legs            50+                  1      1           1
           Wed   Eye             50+                  1      1           1
                 Feet            25-34                1      1           1
Montana    Fri   Multiple        25-34                1      1           1
           Mon   Head            50+                  1      1           1
           Sat   Eye             50+                  1      1           1
           Thu   Trunk           35-49                1      1           1
           Wed   Abdomen         25-34                1      1           1
                 Feet            18-24                1      1           1
                 Multiple        35-49                1      1           1
Ohio       Fri   Back            25-34                1      1           1
           Mon   Hands           18-24                1      1           1
                 Multiple        35-49                1      1           1
           Sat   Multiple        25-34                1      1           1
           Sun   Eye             35-49                1      1           1
           Wed   Back            35-49                1      1           1
                 Eye             18-24                1      1           1
Texas      Mon   Legs            50+                  1      1           1
                 Trunk           25-34                1      1           1
           Thu   Head            18-24                1      1           1
           Tue   Head            18-24                1      1           1
                                 35-49                1      1           1
           Wed   Feet            35-49                1      1           1

                                            Incident Cost  Month  Year
Plant      WkDay Injury Location Age Group
Alabama    Fri   Feet            25-34                  1      1     1
           Mon   Eye             50+                    1      1     1
           Sun   Arms            50+                    1      1     1
                 Back            35-49                  1      1     1
                 Eye             50+                    1      1     1
                 Feet            25-34                  1      1     1
           Tue   Back            50+                    1      1     1
California Fri   Back            35-49                  1      1     1
                 Head            25-34                  1      1     1
           Mon   Trunk           18-24                  1      1     1
           Sun   Abdomen         25-34                  1      1     1
                 Hands           35-49                  1      1     1
                 Head            25-34                  1      1     1
           Thu   Abdomen         18-24                  1      1     1
                 Hands           35-49                  1      1     1
                 Legs            35-49                  1      1     1
           Tue   Hands           50+                    1      1     1
Florida    Fri   Feet            25-34                  1      1     1
                 Multiple        50+                    1      1     1
           Thu   Neck            18-24                  1      1     1
                                 25-34                  1      1     1
Georgia    Fri   Arms            25-34                  1      1     1
           Sun   Abdomen         25-34                  1      1     1
Illinois   Sun   Hands           35-49                  1      1     1
           Thu   Eye             25-34                  1      1     1
           Tue   Back            18-24                  1      1     1
                                 35-49                  1      1     1
Iowa       Sat   Legs            50+                    1      1     1
           Wed   Eye             50+                    1      1     1
                 Feet            25-34                  1      1     1
Montana    Fri   Multiple        25-34                  1      1     1
           Mon   Head            50+                    1      1     1
           Sat   Eye             50+                    1      1     1
           Thu   Trunk           35-49                  1      1     1
           Wed   Abdomen         25-34                  1      1     1
                 Feet            18-24                  1      1     1
                 Multiple        35-49                  1      1     1
Ohio       Fri   Back            25-34                  1      1     1
           Mon   Hands           18-24                  1      1     1
                 Multiple        35-49                  1      1     1
           Sat   Multiple        25-34                  1      1     1
           Sun   Eye             35-49                  1      1     1
           Wed   Back            35-49                  1      1     1
                 Eye             18-24                  1      1     1
Texas      Mon   Legs            50+                    1      1     1
                 Trunk           25-34                  1      1     1
           Thu   Head            18-24                  1      1     1
           Tue   Head            18-24                  1      1     1
                                 35-49                  1      1     1
           Wed   Feet            35-49                  1      1     1

In [12]:
cam = jam.sort_values('Age Group',ascending = False)

In [13]:
cam

,Injury Location,Gender,Age Group,Incident_Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
370,Legs,Male,50+,Crush & Pinch,4.0,Georgia,Lost Time,Night,Purchasing,4771,Fri,9,2021
105,Legs,Male,50+,Crush & Pinch,0.0,Iowa,Near Miss,Afternoon,Administration,0,Fri,6,2020
375,Hands,Female,50+,Cut,0.0,California,First Aid,Night,Purchasing,238,Tue,9,2021
237,Back,Female,50+,Vehicle,0.0,Alabama,Near Miss,Day,Painting,0,Tue,2,2021
236,NaN,Male,50+,Fall,0.5,Illinois,Lost Time,Day,Purchasing,2437,Tue,2,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,Multiple,Male,18-24,Fall,0.0,Ohio,Near Miss,Day,Painting,0,Thu,12,2020
207,Head,Male,18-24,Slip/trip,0.0,Florida,First Aid,Afternoon,Shipping,361,Fri,12,2020
212,Multiple,Male,18-24,Falling object,0.0,Ohio,Near Miss,Afternoon,Painting,0,Wed,12,2020
390,Feet,Male,18-24,Lifting,0.0,Texas,Medical Claim,Day,Finishing,4698,Sat,10,2021
513,Hands,Male,18-24,Vehicle,0.0,Texas,Medical Claim,Afternoon,Melting,706,Tue,6,2022

In [14]:
cam.groupby(['Plant','Shift','Age Group','Injury Location']).count().head(60)

                                                Gender  Incident_Type  \
Plant      Shift     Age Group Injury Location
Alabama    Afternoon 18-24     Arms                  1              1
                               Eye                   1              1
                               Feet                  1              1
                               Head                  1              1
                     25-34     Abdomen               2              2
                               Feet                  1              1
                               Trunk                 1              1
                     35-49     Abdomen               1              1
                               Eye                   1              1
                               Legs                  2              2
                               Neck                  1              1
                     50+       Arms                  1              1
                               Back                  1              1
                               Hands                 1              1
                               Neck                  1              1
           Day       18-24     Eye                   1              1
                               Head                  1              1
                               Neck                  1              1
                               Trunk                 1              1
                     25-34     Back                  1              1
                               Feet                  2              2
                               Hands                 1              1
                               Legs                  1              1
                     35-49     Back                  1              1
                               Feet                  1              1
                     50+       Abdomen               1              1
                               Back                  1              1
                               Eye                   1              1
                               Feet                  1              1
                               Hands                 1              1
           Night     18-24     Arms                  2              2
                               Back                  1              1
                               Feet                  1              1
                               Multiple              1              1
                     25-34     Back                  1              1
                               Legs                  2              2
                               Multiple              1              1
                               Neck                  1              1
                     35-49     Back                  1              1
                               Feet                  1              1
                               Head                  2              2
                               Legs                  1              1
                     50+       Arms                  1              1
                               Eye                   1              1
                               Head                  1              1
                               Neck                  1              1
California Afternoon 18-24     Abdomen               1              1
                               Feet                  1              1
                               Head                  1              1
                     25-34     Abdomen               1              1
                               Back                  1              1
                               Feet                  2              2
                     35-49     Arms                  2              2
                               Feet                  3              3
                               Hands                 2              2
                     50+       Arms                  1              1
           Day       18-24     Eye                   1              1
                               Trunk                 2              2
                     25-34     Abdomen               3              3
                               Arms                  1              1

                                                Days Lost  Report Type  \
Plant      Shift     Age Group Injury Location
Alabama    Afternoon 18-24     Arms                     1            1
                               Eye                      1            1
                               Feet                     1            1
                               Head                     1            1
                     25-34     Abdomen                  2            2
                               Feet                     1            1
                               Trunk                    1            1
                     35-49     Abdomen                  1            1
                               Eye                      1            1
                               Legs                     2            2
                               Neck                     1            1
                     50+       Arms                     1            1
                               Back                     1            1
                               Hands                    1            1
                               Neck                     1            1
           Day       18-24     Eye                      1            1
                               Head                     1            1
                               Neck                     1            1
                               Trunk                    1            1
                     25-34     Back                     1            1
                               Feet                     2            2
                               Hands                    1            1
                               Legs                     1            1
                     35-49     Back                     1            1
                               Feet                     1            1
                     50+       Abdomen                  1            1
                               Back                     1            1
                               Eye                      1            1
                               Feet                     1            1
                               Hands                    1            1
           Night     18-24     Arms                     2            2
                               Back                     1            1
                               Feet                     1            1
                               Multiple                 1            1
                     25-34     Back                     1            1
                               Legs                     2            2
                               Multiple                 1            1
                               Neck                     1            1
                     35-49     Back                     1            1
                               Feet                     1            1
                               Head                     2            2
                               Legs                     1            1
                     50+       Arms                     1            1
                               Eye                      1            1
                               Head                     1            1
                               Neck                     1            1
California Afternoon 18-24     Abdomen                  1            1
                               Feet                     1            1
                               Head                     1            1
                     25-34     Abdomen                  1            1
                               Back                     1            1
                               Feet                     2            2
                     35-49     Arms                     2            2
                               Feet                     3            3
                               Hands                    2            2
                     50+       Arms                     1            1
           Day       18-24     Eye                      1            1
                               Trunk                    2            2
                     25-34     Abdomen                  3            3
                               Arms                     1            1

                                                Department  Incident Cost  \
Plant      Shift     Age Group Injury Location
Alabama    Afternoon 18-24     Arms                      1              1
                               Eye                       1              1
                               Feet                      1              1
                               Head                      1              1
                     25-34     Abdomen                   2              2
                               Feet                      1              1
                               Trunk                     1              1
                     35-49     Abdomen                   1              1
                               Eye                       1              1
                               Legs                      2              2
                               Neck                      1              1
                     50+       Arms                      1              1
                               Back                      1              1
                               Hands                     1              1
                               Neck                      1              1
           Day       18-24     Eye                       1              1
                               Head                      1              1
                               Neck                      1              1
                               Trunk                     1              1
                     25-34     Back                      1              1
                               Feet                      2              2
                               Hands                     1              1
                               Legs                      1              1
                     35-49     Back                      1              1
                               Feet                      1              1
                     50+       Abdomen                   1              1
                               Back                      1              1
                               Eye                       1              1
                               Feet                      1              1
                               Hands                     1              1
           Night     18-24     Arms                      2              2
                               Back                      1              1
                               Feet                      1              1
                               Multiple                  1              1
                     25-34     Back                      1              1
                               Legs                      2              2
                               Multiple                  1              1
                               Neck                      1              1
                     35-49     Back                      1              1
                               Feet                      1              1
                               Head                      2              2
                               Legs                      1              1
                     50+       Arms                      1              1
                               Eye                       1              1
                               Head                      1              1
                               Neck                      1              1
California Afternoon 18-24     Abdomen                   1              1
                               Feet                      1              1
                               Head                      1              1
                     25-34     Abdomen                   1              1
                               Back                      1              1
                               Feet                      2              2
                     35-49     Arms                      2              2
                               Feet                      3              3
                               Hands                     2              2
                     50+       Arms                      1              1
           Day       18-24     Eye                       1              1
                               Trunk                     2              2
                     25-34     Abdomen                   3              3
                               Arms                      1              1

                                                WkDay  Month  Year
Plant      Shift     Age Group Injury Location
Alabama    Afternoon 18-24     Arms                 1      1     1
                               Eye                  1      1     1
                               Feet                 1      1     1
                               Head                 1      1     1
                     25-34     Abdomen              2      2     2
                               Feet                 1      1     1
                               Trunk                1      1     1
                     35-49     Abdomen              1      1     1
                               Eye                  1      1     1
                               Legs                 2      2     2
                               Neck                 1      1     1
                     50+       Arms                 1      1     1
                               Back                 1      1     1
                               Hands                1      1     1
                               Neck                 1      1     1
           Day       18-24     Eye                  1      1     1
                               Head                 1      1     1
                               Neck                 1      1     1
                               Trunk                1      1     1
                     25-34     Back                 1      1     1
                               Feet                 2      2     2
                               Hands                1      1     1
                               Legs                 1      1     1
                     35-49     Back                 1      1     1
                               Feet                 1      1     1
                     50+       Abdomen              1      1     1
                               Back                 1      1     1
                               Eye                  1      1     1
                               Feet                 1      1     1
                               Hands                1      1     1
           Night     18-24     Arms                 2      2     2
                               Back                 1      1     1
                               Feet                 1      1     1
                               Multiple             1      1     1
                     25-34     Back                 1      1     1
                               Legs                 2      2     2
                               Multiple             1      1     1
                               Neck                 1      1     1
                     35-49     Back                 1      1     1
                               Feet                 1      1     1
                               Head                 2      2     2
                               Legs                 1      1     1
                     50+       Arms                 1      1     1
                               Eye                  1      1     1
                               Head                 1      1     1
                               Neck                 1      1     1
California Afternoon 18-24     Abdomen              1      1     1
                               Feet                 1      1     1
                               Head                 1      1     1
                     25-34     Abdomen              1      1     1
                               Back                 1      1     1
                               Feet                 2      2     2
                     35-49     Arms                 2      2     2
                               Feet                 3      3     3
                               Hands                2      2     2
                     50+       Arms                 1      1     1
           Day       18-24     Eye                  1      1     1
                               Trunk                2      2     2
                     25-34     Abdomen              3      3     3
                               Arms                 1      1     1

In [15]:
v = f[f.Incident_Type == 'Burn'].index

In [16]:
cin = f.loc[v,['Plant', 'WkDay','Injury Location','Age Group','Year']]

In [17]:
cin

          Plant WkDay Injury Location Age Group  Year
189  California   Fri            Back     35-49  2020
193     Montana   Wed         Abdomen     25-34  2020
199     Georgia   Fri            Arms     25-34  2020
263        Iowa   Wed            Feet     25-34  2021
279    Illinois   Thu             Eye     25-34  2021
299     Montana   Mon            Head       50+  2021
360       Texas   Tue            Head     35-49  2021

In [18]:
voy = f[f['Injury Location'] == 'Eye'].index

In [19]:
voy

Int64Index([56, 69, 269, 279, 409, 441, 456], dtype='int64')

In [20]:
sri =f.loc[voy,['Plant', 'WkDay','Age Group','Year']]

In [21]:
sri

        Plant WkDay Age Group  Year
56    Alabama   Mon       50+  2020
69    Montana   Sat       50+  2020
269      Ohio   Wed     18-24  2021
279  Illinois   Thu     25-34  2021
409   Alabama   Sun       50+  2021
441      Ohio   Sun     35-49  2022
456      Iowa   Wed       50+  2022

In [22]:
jam

,Injury Location,Gender,Age Group,Incident_Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,Multiple,Male,25-34,Burn,0.0,Iowa,Near Miss,Afternoon,Painting,0,Wed,1,2020
1,NaN,Male,35-49,Vehicle,0.5,Alabama,Lost Time,Day,Fabrication,3367,Fri,1,2020
2,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,0,Fri,1,2020
3,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,0,Sat,1,2020
4,Legs,Male,25-34,Lifting,0.0,Ohio,Near Miss,Day,Painting,0,Tue,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,Head,Female,25-34,Crush & Pinch,0.0,California,First Aid,Night,Administration,77,Sun,6,2022
510,Hands,Male,25-34,Lifting,0.0,Florida,Near Miss,Afternoon,Melting,0,Mon,6,2022
511,Hands,Male,25-34,Cut,0.0,Florida,Near Miss,Afternoon,Purchasing,0,Tue,6,2022
512,Trunk,Male,50+,Falling object,0.0,Florida,Medical Claim,Night,Administration,804,Tue,6,2022
513,Hands,Male,18-24,Vehicle,0.0,Texas,Medical Claim,Afternoon,Melting,706,Tue,6,2022

In [30]:
bol = jam[(jam.Gender == 'Male') & (jam.Year == 2020) & (jam.Plant == 'Iowa')]

In [35]:
bol

,Injury Location,Gender,Age Group,Incident_Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,Multiple,Male,25-34,Burn,0.0,Iowa,Near Miss,Afternoon,Painting,0,Wed,1,2020
6,Neck,Male,25-34,Crush & Pinch,3.5,Iowa,Lost Time,Day,Purchasing,4872,Sat,1,2020
38,Eye,Male,35-49,Burn,0.0,Iowa,Near Miss,Afternoon,Shipping,0,Tue,3,2020
45,Abdomen,Male,25-34,Slip/trip,4.5,Iowa,Lost Time,Day,Fabrication,3146,Tue,3,2020
61,Eye,Male,50+,Burn,0.0,Iowa,First Aid,Afternoon,Painting,155,Thu,4,2020
66,Legs,Male,35-49,Vehicle,0.0,Iowa,First Aid,Day,Administration,281,Wed,4,2020
67,Legs,Male,18-24,Equipment,0.0,Iowa,Near Miss,Afternoon,Security,0,Wed,4,2020
78,Trunk,Male,35-49,Lifting,0.0,Iowa,Near Miss,Day,Administration,0,Sun,5,2020
105,Legs,Male,50+,Crush & Pinch,0.0,Iowa,Near Miss,Afternoon,Administration,0,Fri,6,2020
116,Trunk,Male,25-34,Cut,4.0,Iowa,Lost Time,Night,Finishing,2861,Sun,7,2020
121,Feet,Male,35-49,Cut,0.0,Iowa,Medical Claim,Night,Maintenance,532,Sat,7,2020
133,Trunk,Male,35-49,Equipment,5.0,Iowa,Lost Time,Afternoon,Fabrication,1505,Fri,8,2020
144,Trunk,Male,50+,Slip/trip,0.0,Iowa,First Aid,Night,Administration,242,Fri,8,2020
161,Feet,Male,35-49,Vehicle,0.0,Iowa,First Aid,Night,Administration,133,Fri,9,2020
166,Multiple,Male,35-49,Crush & Pinch,4.5,Iowa,Lost Time,Night,Fabrication,3299,Sun,10,2020
172,Neck,Male,35-49,Burn,0.0,Iowa,First Aid,Day,Shipping,466,Fri,10,2020
176,Hands,Male,25-34,Slip/trip,2.0,Iowa,Lost Time,Night,Fabrication,3549,Thu,10,2020
196,NaN,Male,25-34,Burn,0.0,Iowa,Medical Claim,Day,Melting,1222,Mon,11,2020
208,Abdomen,Male,50+,Equipment,0.0,Iowa,Medical Claim,Afternoon,Maintenance,4176,Sat,12,2020

In [42]:
bol.groupby(['WkDay','Shift','Age Group','Incident_Type','Injury Location']).count()

                                                         Gender  Days Lost  \
WkDay Shift     Age Group Incident_Type Injury Location
Fri   Afternoon 35-49     Equipment     Trunk                 1          1
                50+       Crush & Pinch Legs                  1          1
      Day       35-49     Burn          Neck                  1          1
      Night     35-49     Vehicle       Feet                  1          1
                50+       Slip/trip     Trunk                 1          1
Sat   Afternoon 50+       Equipment     Abdomen               1          1
      Day       25-34     Crush & Pinch Neck                  1          1
      Night     35-49     Cut           Feet                  1          1
Sun   Day       35-49     Lifting       Trunk                 1          1
      Night     25-34     Cut           Trunk                 1          1
                35-49     Crush & Pinch Multiple              1          1
Thu   Afternoon 50+       Burn          Eye                   1          1
      Night     25-34     Slip/trip     Hands                 1          1
Tue   Afternoon 35-49     Burn          Eye                   1          1
      Day       25-34     Slip/trip     Abdomen               1          1
Wed   Afternoon 18-24     Equipment     Legs                  1          1
                25-34     Burn          Multiple              1          1
      Day       35-49     Vehicle       Legs                  1          1

                                                         Plant  Report Type  \
WkDay Shift     Age Group Incident_Type Injury Location
Fri   Afternoon 35-49     Equipment     Trunk                1            1
                50+       Crush & Pinch Legs                 1            1
      Day       35-49     Burn          Neck                 1            1
      Night     35-49     Vehicle       Feet                 1            1
                50+       Slip/trip     Trunk                1            1
Sat   Afternoon 50+       Equipment     Abdomen              1            1
      Day       25-34     Crush & Pinch Neck                 1            1
      Night     35-49     Cut           Feet                 1            1
Sun   Day       35-49     Lifting       Trunk                1            1
      Night     25-34     Cut           Trunk                1            1
                35-49     Crush & Pinch Multiple             1            1
Thu   Afternoon 50+       Burn          Eye                  1            1
      Night     25-34     Slip/trip     Hands                1            1
Tue   Afternoon 35-49     Burn          Eye                  1            1
      Day       25-34     Slip/trip     Abdomen              1            1
Wed   Afternoon 18-24     Equipment     Legs                 1            1
                25-34     Burn          Multiple             1            1
      Day       35-49     Vehicle       Legs                 1            1

                                                         Department  \
WkDay Shift     Age Group Incident_Type Injury Location
Fri   Afternoon 35-49     Equipment     Trunk                     1
                50+       Crush & Pinch Legs                      1
      Day       35-49     Burn          Neck                      1
      Night     35-49     Vehicle       Feet                      1
                50+       Slip/trip     Trunk                     1
Sat   Afternoon 50+       Equipment     Abdomen                   1
      Day       25-34     Crush & Pinch Neck                      1
      Night     35-49     Cut           Feet                      1
Sun   Day       35-49     Lifting       Trunk                     1
      Night     25-34     Cut           Trunk                     1
                35-49     Crush & Pinch Multiple                  1
Thu   Afternoon 50+       Burn          Eye                       1
      Night     25-34     Slip/trip     Hands                     1
Tue   Afternoon 35-49     Burn          Eye                       1
      Day       25-34     Slip/trip     Abdomen                   1
Wed   Afternoon 18-24     Equipment     Legs                      1
                25-34     Burn          Multiple                  1
      Day       35-49     Vehicle       Legs                      1

                                                         Incident Cost  Month  \
WkDay Shift     Age Group Incident_Type Injury Location
Fri   Afternoon 35-49     Equipment     Trunk                        1      1
                50+       Crush & Pinch Legs                         1      1
      Day       35-49     Burn          Neck                         1      1
      Night     35-49     Vehicle       Feet                         1      1
                50+       Slip/trip     Trunk                        1      1
Sat   Afternoon 50+       Equipment     Abdomen                      1      1
      Day       25-34     Crush & Pinch Neck                         1      1
      Night     35-49     Cut           Feet                         1      1
Sun   Day       35-49     Lifting       Trunk                        1      1
      Night     25-34     Cut           Trunk                        1      1
                35-49     Crush & Pinch Multiple                     1      1
Thu   Afternoon 50+       Burn          Eye                          1      1
      Night     25-34     Slip/trip     Hands                        1      1
Tue   Afternoon 35-49     Burn          Eye                          1      1
      Day       25-34     Slip/trip     Abdomen                      1      1
Wed   Afternoon 18-24     Equipment     Legs                         1      1
                25-34     Burn          Multiple                     1      1
      Day       35-49     Vehicle       Legs                         1      1

                                                         Year
WkDay Shift     Age Group Incident_Type Injury Location
Fri   Afternoon 35-49     Equipment     Trunk               1
                50+       Crush & Pinch Legs                1
      Day       35-49     Burn          Neck                1
      Night     35-49     Vehicle       Feet                1
                50+       Slip/trip     Trunk               1
Sat   Afternoon 50+       Equipment     Abdomen             1
      Day       25-34     Crush & Pinch Neck                1
      Night     35-49     Cut           Feet                1
Sun   Day       35-49     Lifting       Trunk               1
      Night     25-34     Cut           Trunk               1
                35-49     Crush & Pinch Multiple            1
Thu   Afternoon 50+       Burn          Eye                 1
      Night     25-34     Slip/trip     Hands               1
Tue   Afternoon 35-49     Burn          Eye                 1
      Day       25-34     Slip/trip     Abdomen             1
Wed   Afternoon 18-24     Equipment     Legs                1
                25-34     Burn          Multiple            1
      Day       35-49     Vehicle       Legs                1

In [46]:
np.random.seed(20)
np.random.randint(4,10,(4,5))

array([[7, 6, 8, 6, 5],
       [8, 7, 6, 4, 4],
       [9, 6, 6, 7, 7],
       [4, 9, 4, 5, 9]])